#!/bin/bash

color=yes
declare blue=$(tput bold; tput setaf 4)
declare green=$(tput bold; tput setaf 2)
declare red=$(tput bold; tput setaf 1)
declare yellow=$(tput bold; tput setaf 3)
declare bold=$(tput bold)
declare reset=$(tput sgr0)

print_targets() {
  local col=$1 name=$2; shift
  local title="$name ($#): "
  local width=$(($(tput cols)-${#title}))
  local i=0
  if [[ $color = yes ]]; then
    printf "${!col}%s$reset" "$title"
  else
    printf "$bold%s$reset" "$title"
  fi
  while read -r line; do
    if ((! i++)); then
      printf "%s\n" "$line"
    else
      printf "%${#title}s%s\n" " " "$line"
    fi
  done < <(fold -sw "$width" <<<"$*")
}

print_targets "blue" "Repo Targets" avidemux-cli-2.5.4-4  avidemux-gtk-2.5.4-4 cifs-utils-4.9-2  ffmpeg-20110330-1  ghostscript-9.02-1 kernel26-2.6.38.2-1  kernel26-headers-2.6.38.2-1 qt-4.7.2-6
print_targets green "AUR Targets" avidemux-cli-2.5.4-4  avidemux-gtk-2.5.4-4 cifs-utils-4.9-2  ffmpeg-20110330-1  ghostscript-9.02-1 kernel26-2.6.38.2-1  kernel26-headers-2.6.38.2-1 qt-4.7.2-6

