#!/bin/bash

################################################################################
# MEAT!!!! simple fast AUR helper, using cower as a back end                   #
################################################################################
# Copyright Daniel Mills <dm@e36freak.com>                                     #
# Wraps 'cower', Copyright Dave Reisner <d@falconindy.com>                     #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of this software and associated documentation files (the "Software"), to     #
# deal in the Software without restriction, including without limitation the   #
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or  #
# sell copies of the Software, and to permit persons to whom the Software is   #
# furnished to do so, subject to the following conditions:                     #
#                                                                              #
# The above copyright notice and this permission notice shall be included in   #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER       #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING      #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS #
# IN THE SOFTWARE.                                                             #
#                                                                              #
# Requires bash4, cower, awk                                                   #
# Optional deps: git (for handling automatic checking of git pkgs)             #
#                sudo (highly recommended)                                     #
################################################################################
# TODO:                                                                        #
#       better function comments/usage descriptions                            #
#       find a better way to handle .install files?                            #
#       write documentation                                                    #
#         make note of default overwriting of existing package dirs            #
#           specify that an alternate target should be used                    #
#       figure out a better way to handle checking for git updates             #
#         handle other VCS systems in the same way                             #
#       find and eliminate redundancies                                        #
#       attempt to minimize calls to pacman, or make it less "interactive"     #
#       !!!!!efficiency!!!!!                                                   #
#       bug squashing                                                          #
#       all kinds of shit :(                                                   #
################################################################################
### Declarations

shopt -s extglob dotglob globstar nullglob

### files
config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/meat # dir for config file
config_file=$config_dir/config                    # config file itself
default_config=/usr/share/meat/config             # default/sample config file
cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/meat    # cache dir
git_sums_file=$cache_dir/gitsums                  # git checksums file
lock_file=$cache_dir/meat.lck                     # lock file

### default values
gitcheck=1                      # boolean, '1' to check git for updates
verbosity=1                     # integer, verbosity level
color=never                     # string, {always,auto,never}
iscolor=(0 0)                   # array, '1' for color on stdout,stderr
t_download_dir=$(mktemp -d)     # tmp target directory for PKGBUILDs, etc
download_dir=$t_download_dir    # will be set for user-specified dir
isuserddir=0                    # boolean, will be set if above is set
gitcheck_dir=$(mktemp -d)       # target directory for git cloning

### default programs
cower=(cower)          # array, cower command and opts
makepkg=(makepkg)      # array, makepkg command and opts
pacman=(pacman)        # array, pacman command and opts

### global variables
# color handling
red=$(tput bold; tput setaf 1)      # bold red
green=$(tput bold; tput setaf 2)    # bold green
yellow=$(tput bold; tput setaf 3)   # bold yellow
blue=$(tput bold; tput setaf 4)     # bold blue
bold=$(tput bold)                   # bold white
reset=$(tput sgr0)                  # reset colors

### option handling
# operations
download=0           # boolean, set for --download
full_update=0        # boolean, set for hidden --fullupdate operation
git_db_update=0      # boolean, set for --git-db-update
info_level=0         # integer, for how many '-i's to pass to cower
                       # also used for checking for --info
msearch=0            # boolean, set for --msearch
op_declared=0        # boolean, if 1 an option has been specified
search=0             # boolean, set for --search
update=0             # boolean, set for --update
sign=0               # boolean, set for --sign
forcenosign=0        # boolean, set for --nosign

# options
addignore=()       # array, used to turn CSV into an array
group_ignore=()    # array, groups to ignore
ignore=()          # array, pkgs to ignore
options=()         # array, opts, used to prepare opts for parsing
optarg=            # used for parsing --foo=bar options
repo_ignore=()     # array, repos to ignore
check_git=0        # boolean, if 1 --git-check has been specified
check_all=0        # boolean, if 1 --check-all has been specified
force=0            # boolean, if 1 --force has been specified
nossl=0            # boolean, if 1 --nossl has been specified
threads=10         # integer, number of threads for cower to create
timeout=10         # integer, cower's timeout time in seconds

### stuff to download
declare -A checked_gits=()  # associative array, key is name, val is sum
cow_targets=()              # stack, list of cower targets
final_cow_targets=()        # array, cower targets in correct order
git_ignore=()               # array, list of packages to ignore for git
pac_targets=()              # array, list of pacman targets
targets=()                  # array, full list of targets
stack_size=0                # integer, size of cow_targets stack
pkg=                        # used when parsing options

################################################################################
### Functions

## build and install AUR packages
# usage: aur_install TARGET_DIR TARGET [...]
aur_install() {
  local pkg newsum toinst pkgs pkgext

  if ! hide 4 pushd "$download_dir"; then
    die "could not cd to \`$download_dir'"
  fi

  # build and install
  for pkg; do
    if ! hide 4 pushd "$pkg"; then
      err "error while changing to dir \`$pkg'"
      continue
    fi

    ## allow user to check files
    checkfiles "$pkg"

    ## build and install package
    until "${makepkg[@]}" -f; do
      if ! confirm "error making package \`$pkg', try again?"; then
        exit 1
      fi
      checkfiles "$pkg"
    done

    # check if package is explicit, or installed as a dep, install accordingly
    info 1 "Installing \`$pkg'..."
    # get PKGEXT from makepkg.conf
    if [[ -n $PKGEXT ]]; then
      pkgext="$PKGEXT"
    else
      IFS= read -rd '' pkgext < <(source /etc/makepkg.conf &&
                                  printf '%s\0' "$PKGEXT")
    fi

    if [[ -z $pkgext ]]; then
      die 'error: missing /etc/makepkg.conf, or PKGEXT unset/empty'
    fi
    pkgs=(*"$pkgext")
    if ((!${#pkgs[@]})); then
      die "error: no package file seems to have been created"
    elif ((${#pkgs[@]} == 1)); then
      toinst=$pkgs
    else
      IFS= read -rd '' toinst < <(printf '%s\0' "${pkgs[@]}" | sort -Vrz)
    fi
    if inarray "$pkg" "${targets[@]}"; then
      if ! hide 1 runasroot "${pacman[@]}" -U "$toinst"; then
        hide 4 popd
        err "something went wrong while installing \`$pkg'"
        continue
      fi
    else
      if ! hide 1 runasroot "${pacman[@]}" -U --asdeps "$toinst"; then
        hide 4 popd
        err "something went wrong while installing \`$pkg'"
        continue
      fi
    fi

    # if package is git, update sums file
    if ((!check_git)) || [[ $pkg != *-git ]]; then
      hide 4 popd
      continue
    fi
    if [[ ${checked_gits[$pkg]} ]]; then
      git_addsum "$pkg" "${checked_gits[$pkg]}"
    else
      if inarray "$pkg" "${git_ignore[@]}"; then
        hide 4 popd
        continue
      fi
      if ! { newsum=$(git_getsum "$pkg" 3>&1 >&4-); } 4>&1; then
        hide 4 popd
        continue
      fi
      git_addsum "$pkg" "$newsum"
    fi

    hide 4 popd
  done
  hide 4 popd
}

### allow user to check PKGBUILD, .install, and other files
# usage: checkfiles PACKAGE
checkfiles() {
  local install file pkg=$1

  ## allow user to edit PKGBUILD and $install
  if confirm "Edit PKGBUILD for \`$pkg'?";then
    ${EDITOR:-vi} PKGBUILD
  fi

  # source PKGBUILD for $install, prompt if exists
  source PKGBUILD
  if [[ $install ]] && confirm "Edit \`$install'?";then
    ${EDITOR:-vi} "$install"
  fi

  # allow for checking every other regular file
  if ((check_all)); then
    for file in ./**/!(PKGBUILD|"$install"); do
      if [[ -f $file && -w $file && $(file "$file") = *text ]] &&
         confirm "Edit \`$file'?";then
        ${EDITOR:-vi} "$file"
      fi
    done
  fi
}

### clean up, clean up, everybody everywhere!
cleanup() {
  rm -rf "$gitcheck_dir" "$tmp"
  if ((!isuserddir)); then
    rm -rf "$download_dir"
  fi
}
    
## ask for confirmation
# usage: confirm [MESSAGE]
confirm() {
  local -l reply        # convert to lowercase on assignment
  local msg=${1:-Continue?}

  # make sure stdin is a terminal
  if [[ ! -t 0 ]]; then
    exec </dev/tty
  fi

  # actually print the prompt, return according to response
  read -p "$bold$msg$reset [Y/n] " reply >/dev/tty
  [[ -z $reply || $reply = y?(es) ]]
}

## print error message, exit
# usage: die MESSAGE [...]
die() { 
  if ((iscolor[1])); then
    printf "$red%s:$reset" "error"
  else
    printf "$bold%s:$reset" "error"
  fi
  printf "\t %s\n" "$@"
  exit 1
} >&2

## download packages, parse cower output for dependency info
# usage: download TARGET [...]
download() {
  local flag pkg info

  info 1 'Cower is downloading packages...'

  # parse cower output, add to stacks
  while read -r flag pkg info; do
    case $flag in
      S) push "$pkg"; info 2 "$info";;
      W) pacadd "$pkg"; info 2 "$info";;
      E) err "$pkg $info";;
      *) err "cower: $flag $pkg $info";;
    esac
  done < <("${cower[@]}" -ddbf "$@" 2>&1)
}

## print error, skip if -f is supplied, else die
# usage: err MESSAGE [...]
err() {
  if ((force)); then
    warn 1 "$@"
  else
    die "$@"
  fi
}

## update the git_sums_file for a given package
# usage: git_addsum NAME SUM
git_addsum() {
  if ! tmp=$(mktemp); then
    die "error creating temp file"
  fi

  if awk -v n="$1" -v s="$2" '$1 != name;
                              END {print n, s}' "$git_sums_file" >"$tmp"; then
    mv "$tmp" "$git_sums_file"
  fi
}

## shallow git clone, rev parse, return current sum
# usage: { sum=$(git_getsum PACKAGE 3>&1 >&4-); } 4>&1
# (aka capture fd 3, leave stdout and stderr intact)
git_getsum() {
  local pkg=$1 newsum _gitroot _gitname

  # delete existing build directories to avoid conflicts
  info 3 "checking for \`$pkg' directory, deleting if it exists"
  if [[ -d $gitcheck_dir/$pkg ]]; then
    rm -rf "$gitcheck_dir/$pkg"
  fi

  # source PKGBUILD, get git source
  info 3 "sourcing PKGBUILD for \`$pkg'"
  if [[ ! -r $download_dir/$pkg/PKGBUILD ]]; then
    if ! hide 2 "${cower[@]}" -d "$pkg"; then
      warn 1 "error downloading PKGBUILD for \`$pkg', skipping"
      return 1
    fi
  fi
  if ! source "$download_dir/$pkg/PKGBUILD"; then
    warn 1 "error sourcing PKGBUILD for \`$pkg', skipping"
    return 1
  fi
      
  # create directory to check git packages, change to dir
  if ! { mkdir -p "$gitcheck_dir" && hide 4 pushd "$gitcheck_dir"; }; then
    die "error creating gitcheck directory \`$gitcheck_dir'"
  fi

  # shallow git clone
  info 2 "cloning git repo for \`$pkg'"
  if ! hide 2 git clone --depth 1 "$_gitroot" "$_gitname"; then
    hide 4 popd
    warn 1 "$_gitname not found in github, check \`$_gitroot', skipping"
    return 1
  fi

  # get current md5sum
  if hide 4 pushd "$_gitname"; then
    if ! newsum=$(git rev-parse origin); then
      warn 1 "error getting md5sum for \`$pkg', skipping"
      return 1
    fi
    hide 4 popd && rm -rf "$_gitname" >/dev/null 2>&1
  else
    hide 4 popd
    warn 1 "error changing dir for \`$pkg', skipping"
    return 1
  fi

  hide 4 popd
  # output sum
  printf '%s' "$newsum" >&3
}

### check if installed git packages are up to date
gitcheck() {
  local pkg tmp newsum oldsum name sum

  # check for updates
  for pkg; do
    # skip ignored packages
    inarray "$pkg" "${git_ignore[@]}" && continue

    # get old md5sum from file
    if ! oldsum=$(awk -v n="$pkg" '$1==n {print $2}' "$git_sums_file"); then
      continue
    fi

    # get new/current md5sum
    if ! { newsum=$(git_getsum "$pkg" 3>&1 >&4-); } 4>&1; then
      continue
    fi

    # compare sums
    if [[ $oldsum = "$newsum" ]]; then
      info 1 "\`$pkg' is up to date"
      continue
    fi

    # this stuff is only done if the md5sums don't match
    info 1 "\`$pkg' is out of date, updating" 
    if ((update)); then
      targets+=("$pkg")
      checked_gits["$pkg"]=$newsum
    else
      git_addsum "$pkg" "$newsum"
    fi
  done
}

## run command, suppressing output according to verbosity
# usage: hide VERBOSITY COMMAND [ARG [...]]
hide() {
  local v=$1; shift

  if ((verbosity >= v)); then
    "$@"
  else
    "$@" >/dev/null 2>&1
  fi
}

## checks if "$needle" is in "${haystack[@]}"
# usage: inarray NEEDLE HAYSTACK [...]
inarray() {
  local val needle=$1; shift

  for val; do
    if [[ $needle = "$val" ]]; then
      return 0
    fi
  done
  return 1
}

## print info message
# usage: info VERBOSITY MESSAGES
info() {
  local v=$1; shift

  if ((verbosity < v)); then
    return
  fi
  printf %s "$bold"
  printf "%s\n" "$@"
  printf %s "$reset"
}

### install everything in "${targets[@]}"
install_all() {
  if ((! ${#targets[@]})); then
    info 1 "there is nothing to do"
    exit 0
  fi

  # download targets, or put in the pacman targets array
  download "${targets[@]}"

  # print lists of targets
  if ((${#cow_targets[@]} || ${#pac_targets[@]})); then
    if ((${#pac_targets[@]})); then
      print_targets "blue" "Repo Targets" "${pac_targets[@]}"
    fi
    if ((${#cow_targets[@]})); then
      print_targets "green" "AUR Targets" "${cow_targets[@]}"
    fi

    echo
    if ! confirm "Proceed with installation?"; then
      exit 0
    fi
  else
    exit 0
  fi

  # install targets in repos
  if ((${#pac_targets[@]})); then
    pac_install "${pac_targets[@]}"
  fi

  ## install AUR targets
  # pop values from stack, make array in the correct order
  while ((stack_size--)); do
    final_cow_targets+=("$(pop)")
  done
  # install AUR targets
  if ((${#final_cow_targets[@]})); then
    aur_install "${final_cow_targets[@]}"
  fi
}

## add value to pacman list
# usage pacadd VALUE [...]
pacadd() {
  pac_targets+=("$@")
}

## install pacman packages
# usage: pac_install TARGET [...]
pac_install() {
  local -a explicits
  local pkg

  hide 1 runasroot "${pacman[@]}" -S --asdeps "$@"
  for pkg; do
    if inarray "$pkg" "${targets[@]}"; then
      explicits+=("$pkg")
    fi
  done
  info 2 "changing packages specified explicitly to have the correct properties"
  hide 2 runasroot "${pacman[@]}" -D --noconfirm --as-explicit "${explicits[@]}"
}

## pop value from top of stack
# usage: value=$(pop)
pop() {
  if ((stack_size < 0)); then
    return 1
  fi
  printf "%s" "${cow_targets[stack_size]}"
}

## print target list
# usage: print_targets COLOR TITLE TARGET [...]
print_targets() {
  local col=$1 name=$2; shift 2
  local title="$name ($#): "
  local width=$(($(tput cols)-${#title}))
  local i=0

  echo
  
  # print title
  if ((iscolor[0])); then
    printf "${!col}%s$reset" "$title"
  else
    printf "$bold%s$reset" "$title"
  fi

  # print list, indented properly
  while read -r line; do
    if ((!i++)); then
      printf "%s\n" "$line"
    else
      printf "%*s%s\n" "${#title}" " " "$line"
    fi
  done < <(fold -sw "$width" <<<"$*")
}

## push value to top of stack
# usage: push 'value'
push() {
  cow_targets[stack_size++]=$1
}

### run command as root
# usage: runasroot COMAND [ARG [...]]
runasroot() {
  if sudo -v >/dev/null 2>&1 && sudo -l "$@" >/dev/null 2>&1; then
    sudo "$@"
  else
    printf "%s " "Root"
    su -c "$(printf '%q ' "$@")"
  fi
}

### sets the color arrays based on options
set_colors() {
  case $color in
    always) iscolor=(1 1);;
    auto)
      if [[ -t 1 ]]; then
        iscolor[0]=1
      else
        iscolor[0]=0
      fi
      if [[ -t 2 ]]; then
        iscolor[1]=1
      else
        iscolor[1]=0
      fi
      ;;
    never) iscolor=(0 0);;
  esac
}

### build arrays to ignore packages
set_ignore_arrays() {
  local IFS=,

  if [[ ${ignore[*]} ]]; then
    cower+=(--ignore="${ignore[*]}")
    pacman+=(--ignore "${ignore[*]}")
  fi
  if [[ ${repo_ignore[*]} ]]; then
    cower+=(--ignorerepo="${repo_ignore[*]}")
  fi
  if [[ ${group_ignore[*]} ]]; then
    pacman+=(--ignoregroup "${group_ignore[*]}")
  fi
}

### full AUR upgrade for installed packages
upgrade() {
  local pkg

  if ((check_git)); then
    gitcheck $(pacman -Qmqs -- -git$)
  fi

  coproc cowout { "${cower[@]}" --color=never -uq; }
  while read -ru "${cowout[0]}" pkg; do
    targets+=("$pkg")
  done

# put this back whenever chet fixes coproc
#  if ! wait "$cowout_PID"; then
#    die "cower error"
#  fi
}

### print usage information
usage() {
cat <<'EOF'
Usage: meat OPERATION [OPTIONS] [TARGET [...]]
  A simple, fast AUR helper written in bash using cower as a back end

 Operations:
  -h, --help              Display this help and exit
  -d, --download          Download and install target(s) -- dependencies will be
                          automatically resolved.
  -G, --git-db-update     Updates the git database with new sums, without
                          actually installing anything (unstable).
  -i, --info              Show info for target(s) -- pass twice for more detail
  -m, --msearch           Show packages maintained by target(s)
  -s, --search            Search AUR for target(s)
  -u, --update            Check for updates against AUR and install them
  -U, --listupdates       Check for updates against AUR and print them -- acts
                          the same way as cower -u

  Only one operation may be specified.

 General options:
  -f, --force             No matter what happens, keep going -- using this
                          option is not recommended
  -g, --git-check         Check and update checksums for git files. (unstable)
      --ignoregit PKG     Ignore PKG when checking for git updates. PKG is a 
                          comma-separated list of packages. May be used more
                          than once
      --ignore PKG        Ignore PKG when upgrading. PKG is a comma-separated
                          list of packages. May be used more than once
      --ignorerepo REPO   Ignore a binary repo. REPO is a comma-separated list
                          of repositories. May be used more than once
      --nossl             Do not use https connections
      --sign              Sign the resulting packages with gpg. Overrides the
                          setting in makepkg.conf(5)
      --nosign            Do not create a signature for built packages. Also
                          overrides makepkg.conf(5)
  -t, --target DIR        Download to DIR, instead of "${TMPDIR:-/tmp}"
      --threads NUM       Limit number of threads created to NUM
      --timeout NUM       Specify connection timeout in seconds
      --check-all         When installing, prompts you to check every regular
                          file in the package directory instead of just the
                          PKGBUILD and .install files

 Output options:
  -c, --color[=WHEN]
        --colour[=WHEN]   Use colored output. WHEN is `never, always, or auto'
      --debug             Show debug output
      --format STRING     Print package output according to STRING
  -q, --quiet             Output less. If both -q and -v are used, each -q is
                          equivalent to removing a -v
  -v, --verbose           Output more. May be specified multiple times for even
                          more information

 Targets:
  Meat accepts a list of targets, space separated. If any target is the single
  character '-', it will also read a list of packages from stdin, one per line.


 Config:
  Meat honors a config file which will be looked for first at:
    $XDG_CONFIG_HOME/meat/config
  And falls back to:
    $HOME/.config/meat/config

  A default documented example can be found at /usr/share/meat/config. If a
  config file does not exist in the above locations when meat runs, the default
  will be copied to the correct location.

 Note:
  It is always recommended to do a full system update (pacman -Syu) before
  installing any new packages, or updating those from the AUR.

 See Also:
  cower(1), pacman(8)

 Author:
  Copyright Daniel Mills <dm@e36freak.com>
  Wraps 'cower', Copyright Dave Reisner <d@falconindy.com>
  Licensing information can be found in the source code

 Bugs:
  Please report any bugs on Github <https://github.com/e36freak/meat>
EOF
}

## print error message
# usage: warn 'verbosity' "messages"
warn() { 
  local v=$1; shift

  if ((verbosity < v)); then
    return 1
  fi
  if ((iscolor[1])); then
    printf "$yellow%s:$reset" "warning"
  else
    printf "$bold%s:$reset" "warning"
  fi
  printf " %s\n" "$1"; shift
  printf "\t %s\n" "$@"
} >&2

################################################################################
### main body of the program
trap cleanup 0

## check for controlling terminal
if ! tput cols >/dev/null 2>&1; then
  die "requires a controlling terminal"
fi

# create cache and config dirs, if not existing
if ! mkdir -p "$cache_dir"; then
  die "cache directory \`$cache_dir' does not exist and could not be created"
fi
if ! mkdir -p "$config_dir"; then
  die "config directory \`$config_dir' does not exist and could not be created"
fi

## get configuration options
if [[ -r $config_file ]]; then
  source "$config_file"

  # check that options are of the correct format
  case $color in
    [01]) info 1 "the boolean value for color is deprecated." \
                 "please change the config to {always,auto,never}"
          if ((color)); then  
            color=auto
          else
            color=never
          fi
          ;;
    always|auto|never) :;;
    *) die "invalid value for \`color' in the config file: \`$color'";;
  esac
  set_colors
  if [[ $nossl != [01] ]]; then
    die "invalid value for \`nossl' in the config file: \`$nossl'"
  fi
  if [[ $check_all != [01] ]]; then
    die "invalid value for \`check_all' in the config file: \`$check_all'"
  fi
  if [[ $timeout = *[![:digit:]]* ]]; then
    die "invalid value for \`timeout' in the config file: \`$timeout'"
  fi
  if [[ $threads = *[![:digit:]]* ]]; then
    die "invalid value for \`threads' in the config file: \`$threads'"
  fi
  if [[ $download_dir != "$t_download_dir" ]]; then
    isuserddir=1
  fi
else
  if cp "$default_config" "$config_file"; then
    info 1 "a default config file has been created at \`$config_file'"
  else
    warn 1 "error copying config file \`$default_config' to \`$config_file'" \
           "reverting to default values."
  fi
fi


## parse options
# option string for splitting short options, any letter followed by a ':' takes
# a required argument
optstring=hdGimsuUfgt:cqv

# iterate over options, breaking -ab into -a -b. also turns -- into --endopts to
# avoid issues with things like '-o-', the '-' should not indicate the end of
# options, but be an invalid option (or the option's arg, such as wget -qO-)
unset options
while (($#)); do
  case $1 in
    # if option is of type -ab
    -[!-]?*)
      # loop over each character starting with the second
      for ((i=1; i<${#1}; i++)); do
        c=${1:i:1}
        
        # add current char to options
        options+=("-$c")

        # if option takes a required argument, and it's not the last char
        # make the rest of the string its argument
        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
          options+=("${1:i+1}")
          break
        fi
      done
      ;;
    # end of options, stop breaking them up
    --)
      options+=(--endopts)
      shift
      options+=("$@")
      break
      ;;
    # otherwise, nothing special
    *) options+=("$1");;
  esac

  shift
done
# set new positional parameters to altered options
set -- "${options[@]}"
unset options

# build commands, set operations, etc
while [[ $1 = -?* ]]; do
  case $1 in
    # operations
    -h|--help|-\?) usage >&2; exit;;
    -d|--download) ((op_declared++)); download=1;;
    -i|--info) ((!info_level && op_declared++)); ((info_level++));;
    -m|--msearch) ((op_declared++)); msearch=1;;
    -s|--search) ((op_declared++)); search=1;;
    -u|--update) ((op_declared++)); update=1;;
    -U|--listupdates) ((op_declared++)); list_updates=1;;
    -G|--git-db-update) ((op_declared++)); git_db_update=1;;
    --fullupdate) ((op_declared++)); full_update=1;;

    # options
    -c|--colo?(u)r?(=*))
      if [[ $1 = --colo?(u)r=* ]]; then
        optarg=${1#*=}
        case $optarg in
          always|auto|never) color=$optarg;;
          *) 
            if [[ $1 = --colour* ]]; then
              die "invalid colour type: $optarg"
            else
              die "invalid color type: $optarg"
            fi
            ;;
        esac
      else
        color=auto
      fi
      ;;
    -v|--verbose|--debug)
      if [[ $1 = --debug ]]; then
        verbosity=4
      else
        ((verbosity++))
      fi
      ;;
    -q|--quiet) ((verbosity > 0 && verbosity--));;
    -f|--force) force=1;;
    --format?(=*))
      if [[ $1 = --format=* ]]; then
        cower+=("--format" "${1#*=}")
      elif [[ $2 ]]; then
        cower+=("--format" "$2")
      else
        die "no format given for $1"
      fi
      ;;
    --ignore?(=*))
      if [[ $1 = --ignore=* ]]; then
        optarg=${1#*=}
      elif [[ $2 ]]; then
        optarg=$2
        shift
      else 
        die "no targets given for $1"
      fi
      if [[ $optarg = *\ * ]]; then
        die "invalid ignore list format for $1"
      fi

      IFS=, read -ra addignore <<<"$optarg"
      ignore+=("${addignore[@]}")
      ;;
    --ignorerepo?(=*))
      if [[ $1 = --ignorerepo=* ]]; then
        optarg=${1#*=}
      elif [[ $2 ]]; then
        optarg=$2
        shift
      else 
        die "no targets given for $1"
      fi
      if [[ $optarg = *\ * ]]; then
        die "invalid ignore list format for $1"
      fi

      IFS=, read -ra addignore <<<"$optarg"
      repo_ignore+=("${addignore[@]}")
      ;;
    --ignoregroup?(=*))
      if [[ $1 = --ignoregroup=* ]]; then
        optarg=${1#*=}
      elif [[ $2 ]]; then
        optarg=$2
        shift
      else 
        die "no targets given for $1"
      fi
      if [[ $optarg = *\ * ]]; then
        die "invalid ignore list format for $1"
      fi

      IFS=, read -ra addignore <<<"$optarg"
      group_ignore+=("${addignore[@]}")
      ;;
    --ignoregit?(=*))
      if [[ $1 = --ignoregit=* ]]; then
        optarg=${1#*=}
      elif [[ $2 ]]; then
        optarg=$2
        shift
      else 
        die "no targets given for $1"
      fi
      if [[ $optarg = *\ * ]]; then
        die "invalid ignore list format for $1"
      fi

      IFS=, read -ra addignore <<<"$optarg"
      git_ignore+=("${addignore[@]}")
      ;;
    --nossl) nossl=1;;
    --sign) sign=1; forcenosign=0;;
    --nosign) sign=0; forcenosign=1;;
    -t|--target?(=*))
      if [[ $1 = --target=* ]]; then
        optarg=${1#*=}
      elif [[ $2 ]]; then
        optarg=$2
        shift
      else
        die "no target specified for $1"
      fi
      download_dir=$optarg
      ;;
    --threads?(=*))
      if [[ $1 = --threads=* ]]; then
        optarg=${1#*=}
      elif [[ $2 = +([[:digit:]]) ]]; then
        optarg=$2
        shift
      else
        die "invalid number of threads: $2"
      fi
      threads=$optarg
      ;;
    --timeout)
      if [[ $1 = --timeout=* ]]; then
        optarg=${1#*=}
      elif [[ $2 = +([[:digit:]]) ]]; then
        optarg=$2
        shift
      else
        die "invalid value for timeout: $2"
      fi
      timeout=$optarg
      ;;
    -g|--git-check) check_git=1;;
    --check-all) check_all=1;;

    # end of options
    --endopts) shift; break;;

    # check for invalid options
    *)
      case $1 in
        --?*) die "invalid option: \`$1'";;
        *) die "invalid option: \`${1#-}'";;
      esac
      ;;
  esac

  shift
done


## this script should not be run as root!
if ((!UID)); then
  die "do not run this script as root" \
      "you will prompted for the sudo/root password when needed"
fi
  
# option error handling, format checking
if ((op_declared > 1)); then
  die 'only one operation may be specified'
elif ((! op_declared)); then
  die 'no operation specified'
fi
if ((git_check && !update)); then
  die '--git-check may only be used with -u (--update)'
fi

# get targets, from stdin and positional parameters
while (($#)); do
  case $1 in
    -?*)
      die "$1: invalid package name" \
          "all operations and options must be specified before packages"
      ;;
    -)
      if [[ -t 0 ]]; then
        die "unable to read stdin for packages"
      else
        while read -r pkg; do
          targets+=("$pkg")
        done
      fi
      shift
      ;;
    *) targets+=("$1"); shift;;
  esac
done

# color info
if ((iscolor[0])); then
  pacman+=(--color=always)
  cower+=(--color=always) 
else
  makepkg+=(-m)
  cower+=(--color=never)
fi

## finish building makepkg
if ((sign)); then
  makepkg+=(--sign)
elif ((forcenosign)); then
  makepkg+=(--nosign)
fi

## build cower and pacman base commands from options
# verbosity
### cower stuff has been commented out as a bug workaround
if ((verbosity >= 3)); then
  if ((verbosity >= 4)); then
    pacman+=(--debug)
    #cower+=(--debug)
  else
    pacman+=(-v)
    #cower+=(-v)
  fi
elif ((! verbosity)); then
  pacman+=(-q)
  cower+=(-q)
fi

# timeout
if ((timeout != 10)); then
  cower+=(--timeout "$timeout")
fi
# nossl
if ((nossl)); then
  cower+=(--nossl)
fi
# threads
if ((threads != 10)); then
  cower+=("--threads" "$2")
fi

# default download dir, pass to cower
cower+=(-t "$download_dir")

# packages to ignore
set_ignore_arrays

### files and directories
# make sure download dir exists
if ! mkdir -p "$download_dir"; then
  die "download dir \`$download_dir' can't be created" \
      "check permissions"
fi
# create git sums file, if not existing
if ! touch "$git_sums_file"; then
  die "\`$git_sums_file' does not exist and could not be created"
fi

### lock file handling
{
if ! flock -n 9; then
  die "only one instance of meat may be running at a time." \
      "if you are sure that another instance isn't running," \
      "remove \`$lock_file'"
fi
                
## finally, we get to do shit!!!
# --download, -d
if ((download)); then
  if ((!${#targets[@]})); then
    die "no targets specified"
  fi
  install_all

# --info, -i
elif ((info_level)); then
  if ((!${#targets[@]})); then
    die "no targets specified"
  fi
  if ((info_level == 1)); then
    "${cower[@]}" -i "${targets[@]}"
  else
    "${cower[@]}" -ii "${targets[@]}"
  fi

# --msearch, -m
elif ((msearch)); then
  if ((!${#targets[@]})); then
    die "no targets specified"
  fi
  "${cower[@]}" -m "${targets[@]}"

# --search, -s
elif ((search)); then
  if ((!${#targets[@]})); then
    die "no targets specified"
  fi
  "${cower[@]}" -s "${targets[@]}"

# --update, -u
elif ((update)); then
  upgrade
  install_all

# --listupdates, -U
elif ((list_updates)); then
  "${cower[@]}" -u "${targets[@]}"

# --git-db-update, -G
elif ((git_db_update)); then
  if ((${#targets[@]})); then
    gitcheck "${targets[@]}"
  else
    gitcheck $(pacman -Qmqs -- -git$)
  fi
  info 1 'git database updated successfully'

# --fullupdate
elif ((full_update)); then
  runasroot "${pacman[@]}" -Syu
  upgrade
  install_all

# ZOMG
else
  die "this should never been seen, report a bug"
fi
} 9>"$lock_file"

# vim: set ts=2 et
